# Generated by Django 5.2.4 on 2025-07-19 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='art_style',
            field=models.CharField(blank=True, choices=[('abstract', 'Abstract'), ('realistic', 'Realistic'), ('contemporary', 'Contemporary'), ('traditional', 'Traditional'), ('modern', 'Modern'), ('folk', 'Folk Art'), ('minimalist', 'Minimalist'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='artist_statement',
            field=models.TextField(blank=True, help_text='Tell the story behind your artwork', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='dimensions',
            field=models.CharField(blank=True, help_text='e.g., 24" x 36" or 60cm x 90cm', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='materials',
            field=models.TextField(blank=True, help_text='List the eco-friendly materials used', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sustainability_rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, help_text='How eco-friendly is this piece? (1-5)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('painting', 'Eco Paintings'), ('sculpture', 'Recycled Sculptures'), ('textile', 'Sustainable Textiles'), ('jewelry', 'Eco Jewelry'), ('paper', 'Recycled Paper Art'), ('mixed_media', 'Mixed Media'), ('digital', 'Digital Eco Art'), ('other', 'Other')], max_length=20),
        ),
    ]
