# Generated by Django 5.2.4 on 2025-07-19 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_product_art_style_product_artist_statement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='art_style',
            field=models.CharField(blank=True, choices=[('abstract', 'Abstract'), ('realistic', 'Realistic'), ('contemporary', 'Contemporary'), ('traditional', 'Traditional'), ('modern', 'Modern'), ('folk', 'Folk Art'), ('minimalist', 'Minimalist'), ('steampunk', 'Steampunk'), ('collage', 'Collage'), ('sculptural', 'Sculptural'), ('wearable', 'Wearable Art'), ('functional', 'Functional Art'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('eco_jewelry', '🌿 Eco Jewelry'), ('recycled_sculptures', '🔩 Recycled Metal Sculptures'), ('wall_art', '🎨 Wall Art & Fine Art'), ('home_decor', '🏠 Home Decor & Sculptures'), ('handmade_artisan', '🔨 Handmade & Artisan Products'), ('natural_sustainable', '🌱 Natural & Sustainable Products'), ('sustainable_fashion', '👕 Sustainable Fashion'), ('showcase_educational', '📸 Showcase & Educational'), ('other', '✨ Other')], max_length=20),
        ),
    ]
