# Generated by Django 5.2.4 on 2025-07-19 23:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('review_received', 'Review Received'), ('order_placed', 'Order Placed'), ('order_status_changed', 'Order Status Changed'), ('product_added_to_cart', 'Product Added to Cart'), ('product_removed_from_cart', 'Product Removed from Cart'), ('product_added_to_wishlist', 'Product Added to Wishlist'), ('product_removed_from_wishlist', 'Product Removed from Wishlist'), ('new_follower', 'New Follower'), ('product_liked', 'Product Liked'), ('product_shared', 'Product Shared'), ('welcome', 'Welcome'), ('system', 'System')], max_length=50),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='market.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-added_at'],
                'unique_together': {('user', 'product')},
            },
        ),
    ]
